meilisearch/meilisearch-java

README.md, build.gradle, src/main/java/meilisearch/Index.java, src/main/java/meilisearch/Indexes.java, src/main/java/meilisearch/MSClient.java, src/main/java/meilisearch/Request.java, src/test/java/meilisearch/IndexesTest.java
=> Fix index API

build.gradle, src/main/java/meilisearch/Documents.java, src/main/java/meilisearch/Indexes.java, src/main/java/meilisearch/UpdateStatus.java, src/test/java/meilisearch/DocumentsTest.java
=> add 'update' API

CONTRIBUTING.md, LICENSE, README.md
=> Add README layout and structure, CONTRIBUTING and LICENSE files

README.md
The imported class is not used in the Getting started
=> Remove unused import from Getting started in README.md

src/main/java/meilisearch/UpdateStatus.java
=> Add error message, error code and error link to the UpdateStatus Class

CONTRIBUTING.md, README.md
=> Update readme (installation guide and getting started) and contributing

.editorconfig, CONTRIBUTING.md, README.md, build.gradle, settings.gradle
- Update CONTRIBUTING.md
- Update the README -> this is not a WIP anymore 🎉
=> Update documentation files

src/main/java/com/meilisearch/sdk/Search.java, src/main/java/com/meilisearch/sdk/SearchRequest.java, src/test/java/com/meilisearch/sdk/SearchRequestTest.java
Change of method in Search Java
For the issue: Migrate search from GET to POST #54
=> Change of get method to post method in the sdk

src/main/java/com/meilisearch/sdk/Documents.java, src/main/java/com/meilisearch/sdk/Index.java, src/test/java/com/meilisearch/integration/DocumentsTest.java
Added update method and its respective test for issue #79 . I only make the test with one document to update, tell me if you need a test with multiple documents to update.
=> Added update method with the test

README.md, src/main/java/com/meilisearch/sdk/Client.java, src/main/java/com/meilisearch/sdk/Index.java, src/main/java/com/meilisearch/sdk/IndexesHandler.java, src/test/java/com/meilisearch/integration/ClientTest.java, src/test/java/com/meilisearch/integration/DocumentsTest.java, src/test/java/com/meilisearch/integration/SearchTest.java, src/test/java/com/meilisearch/integration/UpdatesTest.java
=> Changes due to the implicit index creation

src/test/java/com/meilisearch/integration/DocumentsTest.java
I just added a new test update multiple documents, if there's anything wrong or you have a comment please let me know.
=> Test update for multiple documents

src/main/java/com/meilisearch/sdk/Client.java, src/main/java/com/meilisearch/sdk/Config.java, src/main/java/com/meilisearch/sdk/Documents.java, src/main/java/com/meilisearch/sdk/MeiliSearchHttpRequest.java, src/main/java/com/meilisearch/sdk/Search.java, src/main/java/com/meilisearch/sdk/SearchRequest.java, src/main/java/com/meilisearch/sdk/UpdateStatus.java, src/main/java/com/meilisearch/sdk/Updates.java, src/main/java/com/meilisearch/sdk/exceptions/MeiliSearchCommunicationException.java
https://github.com/meilisearch/meilisearch-java/issues/71
This isn't exhaustive but what I was able to gather so far in one evening of looking at the code. Please let me know what I have gotten right and wrong up to this point so I can be more accurate in later commits
=> Added some documentation

build.gradle, src/main/java/com/meilisearch/sdk/json/JsonbJsonHandler.java, src/test/java/com/meilisearch/sdk/json/JsonbJsonHandlerTest.java
=> fix yasson version

src/main/java/com/meilisearch/sdk/Client.java, src/main/java/com/meilisearch/sdk/Dump.java, src/main/java/com/meilisearch/sdk/DumpHandler.java, src/test/java/com/meilisearch/integration/ClientTest.java, src/test/java/com/meilisearch/integration/SearchTest.java
Closes #35.
This PR implements the dumps route of the MeiliSearch API. 
For more details about dumps: https://docs.meilisearch.com/references/dump.html
The new class `Dump` works as a wrapper for `MeiliSearchRequestHttp` and handles the creation of the dump with the method `createDump`. This method returns a Dump object which contains:
- `uid` that is the unique identifier of the dump
- `status` which indicates the status of the dump at the moment of the call
The method `createDump` is finally called by the `Client` class in a method of its own, that also returns an instance of Dump.
Very similar to the previous point, it uses the new `Dump` class in coordination with the `Client` class to make an HTTP GET request and retrieve the current information of the dump. It uses the method …
=> Implement dumps

src/main/java/com/meilisearch/sdk/Client.java
Minor fixes about styling introduced by https://github.com/meilisearch/meilisearch-java/pull/89.
=> Fix bad styling

src/main/java/com/meilisearch/sdk/Client.java, src/main/java/com/meilisearch/sdk/Config.java, src/main/java/com/meilisearch/sdk/Documents.java, src/main/java/com/meilisearch/sdk/Dump.java, src/main/java/com/meilisearch/sdk/DumpHandler.java, src/main/java/com/meilisearch/sdk/Index.java, src/main/java/com/meilisearch/sdk/IndexesHandler.java, src/main/java/com/meilisearch/sdk/MeiliSearchHttpRequest.java, src/main/java/com/meilisearch/sdk/Search.java, src/main/java/com/meilisearch/sdk/SettingsHandler.java, src/main/java/com/meilisearch/sdk/Updates.java
Hello.
I've found that usage of 'Meilisearch' and 'MeiliSearch' are mixed in this project. Seems official naming are 'MeiliSearch', so I updated the comments.
Please look on 🙏
=> Unify project name as `MeiliSearch` in comments

src/main/java/com/meilisearch/sdk/http/request/BasicHttpRequest.java
I just tried to fix this for the POC i'm trying to build ... 
So I'm not sure you'll want to pull this, but there seems to be a problem there so ...
Thank you for the sdk !
=> [Enconding UTF-8 BasicHttpRequest] "fix" issue 131

README.md
Update version on readme on 0.3.0 release
=> Update version on README

README.md
Reverts meilisearch/meilisearch-java#136
=> Revert "Update version on README"

build.gradle
Reverts meilisearch/meilisearch-java#135
=> Revert "Update version on build.gradle"

src/main/java/com/meilisearch/sdk/api/keys/KeysHandler.java, src/test/java/com/meilisearch/integration/ExceptionsTest.java, src/test/java/com/meilisearch/sdk/api/keys/KeysHandlerTest.java
⚠️ This PR includes #120 and #121 
This AP contains the API for the /keys endpoint.
=> implement Keys API based on ServiceTemplate 

README.md, build.gradle
- Update README.md and build.gradle to v0.3.0
=> Update version from v0.2.0 to v0.3.0

.github/scripts/check-release.sh, .github/workflows/ossrh-publish.yml
Closes #140 
I tested it this way to "immitate" the GitHub action behavior:
=> Add check release script

CONTRIBUTING.md
The setup part with `./gradlew install` was not possible to use
=> Remove the setup part from CONTRIBUTING.md

.github/workflows/pre-release-tests.yml
This `if` should not be present in this GHA file 🙂
=> Fix pre-release CI test

src/test/java/com/meilisearch/sdk/json/JsonbJsonHandlerTest.java
=> Add cast to remove warning

src/main/java/com/meilisearch/sdk/api/instance/InstanceHandler.java, src/test/java/com/meilisearch/sdk/api/instance/InstanceHandlerTest.java
**Description**
Checking that method health() return {'status': 'available'} and added isHealthy() method who return boolean value
**Issue related**
meilisearch/integration-guides#55
=> Standardize health method

src/main/java/com/meilisearch/sdk/Search.java, src/main/java/com/meilisearch/sdk/SearchRequest.java, src/main/java/com/meilisearch/sdk/api/documents/SearchRequest.java, src/test/java/com/meilisearch/integration/SearchTest.java, src/test/java/com/meilisearch/sdk/SearchRequestTest.java
- Use `filter` instead of `filters`
=> Rename Filters into Filter

src/test/java/com/meilisearch/integration/DocumentsTest.java, src/test/java/com/meilisearch/integration/SearchTest.java, src/test/java/com/meilisearch/integration/SettingsTest.java
Adapts tests according to v0.21.0 breaking changes.
=> Fix a part of the tests

src/main/java/com/meilisearch/sdk/Search.java, src/main/java/com/meilisearch/sdk/SearchRequest.java, src/test/java/com/meilisearch/sdk/SearchRequestTest.java
- Adding the fields `facetsDistribution` in Search #184
=> Add facets distribution fields in search request

src/main/java/com/meilisearch/sdk/Search.java, src/main/java/com/meilisearch/sdk/SearchRequest.java, src/main/java/com/meilisearch/sdk/api/documents/SearchRequest.java, src/test/java/com/meilisearch/integration/SearchTest.java, src/test/java/com/meilisearch/sdk/SearchRequestTest.java
=> #197: Add support for filter arrays and nested filters

README.md
Fixes #67 
I think this looks cleaner and also removes the hassle of escaping quotes.
=> Implemented a better way to add documents in the Getting Started code example

src/main/java/com/meilisearch/sdk/Documents.java, src/main/java/com/meilisearch/sdk/Index.java, src/test/java/com/meilisearch/integration/DocumentsTest.java
=> #78: addDocuments and updateDocuments should take pk as optional param

.code-samples.meilisearch.yaml, README.md, build.gradle
Updating version of the package
=> Update release v0.6.0

src/main/java/com/meilisearch/sdk/api/instance/IndexStats.java, src/main/java/com/meilisearch/sdk/api/instance/Stats.java, src/test/java/com/meilisearch/sdk/api/instance/InstanceHandlerTest.java
Fixes #298 
Thank you so much for contributing to MeiliSearch!
=> Change type for variable of databaseSize

src/main/java/com/meilisearch/sdk/UpdateStatus.java, src/main/java/com/meilisearch/sdk/UpdateStatusError.java, src/test/java/com/meilisearch/integration/ExceptionsTest.java
=> make Class Error accesible

src/main/java/com/meilisearch/sdk/Index.java, src/test/java/com/meilisearch/integration/DocumentsTest.java
Fixes #232 
Thank you so much for contributing to MeiliSearch!
=> #232 add add documents in batches and update documents in batches

src/main/java/com/meilisearch/sdk/http/ApacheHttpClient.java, src/main/java/com/meilisearch/sdk/http/CustomOkHttpClient.java, src/main/java/com/meilisearch/sdk/http/DefaultHttpClient.java
=> Use Authorization header instead of X-Meili-API-Key

.code-samples.meilisearch.yaml
Add new code samples due to changes related to v0.25.0
=> Adding new code samples

.github/workflows/ossrh-publish.yml, .github/workflows/tests.yml, src/test/java/com/meilisearch/integration/KeysTest.java
Fixing the failed build on the `deploy` stage in Github Actions
Add test result in `Artifacts`
=> Fix error in build during `deploy` and add `Artifacts` to Github actions

.code-samples.meilisearch.yaml, README.md
Update to the version 0.7.2 in the missing files.
=> Update version for the next release (v0.7.2)

README.md
=> changed genre to genres

src/main/java/com/meilisearch/sdk/model/Key.java, src/main/java/com/meilisearch/sdk/model/Result.java, src/main/java/com/meilisearch/sdk/model/Task.java, src/test/java/com/meilisearch/integration/DocumentsTest.java, src/test/java/com/meilisearch/integration/ExceptionsTest.java, src/test/java/com/meilisearch/integration/KeysTest.java, src/test/java/com/meilisearch/integration/SearchTest.java, src/test/java/com/meilisearch/integration/SettingsTest.java, src/test/java/com/meilisearch/integration/TasksTest.java, src/test/java/com/meilisearch/integration/TenantTokenTest.java
Replace the name`Meilisearch` with the correct typo where it remained.
**Notes**:
`MeiliSearchHttpRequest` will be change in the same time as the Client.
=> Renaming last  MeiliSearch to Meilisearch

CONTRIBUTING.md, src/main/java/com/meilisearch/sdk/Client.java, src/main/java/com/meilisearch/sdk/Documents.java, src/main/java/com/meilisearch/sdk/HttpClient.java, src/main/java/com/meilisearch/sdk/Index.java, src/main/java/com/meilisearch/sdk/IndexesHandler.java, src/main/java/com/meilisearch/sdk/InstanceHandler.java, src/main/java/com/meilisearch/sdk/KeysHandler.java, src/main/java/com/meilisearch/sdk/SettingsHandler.java, src/main/java/com/meilisearch/sdk/TasksHandler.java
- Unify methods definitions
- Add link to methods definitions if not present
- Remove public from method in Handler
=> Unify methods definitions

.code-samples.meilisearch.yaml, src/main/java/com/meilisearch/sdk/Client.java, src/test/java/com/meilisearch/integration/ClientTest.java, src/test/java/com/meilisearch/integration/classes/AbstractIT.java
This PR rename the method `getAllIndexes()` to `getIndexes()`
=> Rename getAllIndexes in getIndexes

.editorconfig, .gitignore, build.gradle
- Set the indent_style to "space" instead of "tabs".
- Enable test reports to be forwarded to Docker volume
- Allow debugging output from env var.
=> Developer experience enhancements

src/main/java/com/meilisearch/sdk/http/URLBuilder.java, src/test/java/com/meilisearch/sdk/http/URLBuilderTest.java
The v0.28.0 version has added the possibility to filter the results via query parameters.
A new Class `URLBuilder` has been added in this PR to help create URLs with query parameters
=> Add URLBuilder for query parameters

src/main/java/com/meilisearch/sdk/TasksHandler.java, src/main/java/com/meilisearch/sdk/model/Task.java, src/main/java/com/meilisearch/sdk/model/TaskInfo.java, src/main/java/com/meilisearch/sdk/model/TaskStatus.java, src/test/java/com/meilisearch/integration/ClientTest.java, src/test/java/com/meilisearch/integration/TasksTest.java
Task status enum on model package, added on task and taskInfo and modified some tests.
Fixes #556 
* TaskStatus enum added in model directory
* String status in the Task and TaskInfo class exchanged with new enum
* Some tests rewritten with the new use of the enum
I have a question. While changing some test I found out that when trying to do .waitForTask a NullPointerException was happening, even tho this not affect directly to what I'm implementing I don't wanna move something that can make it break, I also built  everything and  tested with ./gradlew test and lint. This is a draft so maybe you can check it out and let me know what you think
=> feat: created Task Status enum.

.code-samples.meilisearch.yaml, src/main/java/com/meilisearch/sdk/Index.java, src/main/java/com/meilisearch/sdk/SettingsHandler.java, src/test/java/com/meilisearch/integration/SettingsTest.java
Fixes #491 
It applies the code review suggested changes from the last pull request.
- getSortableAttributesSettings
- updateSortableAttributesSettings
- resetSortableAttributesSettings
- Add tests
- Add sample in the code-sample file
[yes] Does this PR fix an existing issue, or have you listed the changes applied in the PR description (and why they are needed)?
[yes] Have you read the contributing guidelines?
[yes] Have you made sure that the title is accurate and descriptive of the changes?
=> add methods for sortable attributes settings

src/test/java/com/meilisearch/integration/TasksTest.java
Fixes #501 
- improves testClientGetTasks() to avoid looping all elements
=> improve testClientGetTasks() to avoid looping all elements

.github/workflows/tests.yml, README.md
Fixes #641
- Added CodeCov Config
=> meilisearch-java #641: Added CodeCov Config

.code-samples.meilisearch.yaml
=> Update code samples for april 2023

src/main/java/com/meilisearch/sdk/TasksHandler.java
Fixes #669 
- Add re-interrupt line
- Declare exception class
=> Add re-interrupt to waitForTask method

src/main/java/com/meilisearch/sdk/Client.java, src/main/java/com/meilisearch/sdk/Documents.java, src/main/java/com/meilisearch/sdk/Index.java, src/main/java/com/meilisearch/sdk/IndexesHandler.java, src/main/java/com/meilisearch/sdk/InstanceHandler.java, src/main/java/com/meilisearch/sdk/KeysHandler.java, src/main/java/com/meilisearch/sdk/Search.java, src/main/java/com/meilisearch/sdk/SettingsHandler.java, src/main/java/com/meilisearch/sdk/TasksHandler.java, src/main/java/com/meilisearch/sdk/model/CancelTasksQuery.java, src/main/java/com/meilisearch/sdk/model/DeleteTasksQuery.java, src/main/java/com/meilisearch/sdk/model/DocumentQuery.java, src/main/java/com/meilisearch/sdk/model/DocumentsQuery.java, src/main/java/com/meilisearch/sdk/model/IndexStats.java, src/main/java/com/meilisearch/sdk/model/IndexesQuery.java, src/main/java/com/meilisearch/sdk/model/Key.java, src/main/java/com/meilisearch/sdk/model/KeyUpdate.java, src/main/java/com/meilisearch/sdk/model/KeysQuery.java, src/main/java/com/meilisearch/sdk/model/SearchResult.java, src/main/java/com/meilisearch/sdk/model/SearchResultPaginated.java, src/main/java/com/meilisearch/sdk/model/Searchable.java, src/main/java/com/meilisearch/sdk/model/Settings.java, src/main/java/com/meilisearch/sdk/model/Stats.java, src/main/java/com/meilisearch/sdk/model/Task.java, src/main/java/com/meilisearch/sdk/model/TaskInfo.java, src/main/java/com/meilisearch/sdk/model/TaskStatus.java, src/main/java/com/meilisearch/sdk/model/TasksQuery.java, src/main/java/com/meilisearch/sdk/model/TasksResults.java, src/main/java/com/meilisearch/sdk/model/TypoTolerance.java
Fixes #668 
- Make hyperlink to javadoc using `<a>` and `@see`
- Fix a few URLs
=> Change reference url in javadoc to see tag

src/main/java/com/meilisearch/sdk/model/Searchable.java
Fixes #676
- fixed the URL to work.
=> Fix invalid reference url in Searchable

.code-samples.meilisearch.yaml, src/main/java/com/meilisearch/sdk/Client.java, src/test/java/com/meilisearch/integration/ClientTest.java
Fixes #686
- Add a new method, 'createSnapshot()' , to Client class to create snapshots via the route POST '/snapshots'
=> Add createSnapshot() method

.code-samples.meilisearch.yaml, src/main/java/com/meilisearch/sdk/Index.java, src/main/java/com/meilisearch/sdk/SettingsHandler.java, src/main/java/com/meilisearch/sdk/model/Settings.java, src/test/java/com/meilisearch/integration/SettingsTest.java
Fixes #702
- This PR adds support for the newly introduced proximity precision level feature introduced in v1.6, adds integration tests for the new methods and updates code samples to show how to use the newly added feature. 
=> Add proximity precision settings support

src/main/java/com/meilisearch/sdk/TasksHandler.java
Fixes #725
- fix WaitForTask timeout in case of a task cancellation
=> fix WaitForTask timeout in case of a task cancellation

.code-samples.meilisearch.yaml, src/main/java/com/meilisearch/sdk/SearchRequest.java, src/test/java/com/meilisearch/integration/SearchTest.java, src/test/java/com/meilisearch/sdk/utils/Movie.java
Fixes #632
- Add ranking score search parameter
=> Add ranking score search parameter

.code-samples.meilisearch.yaml, src/main/java/com/meilisearch/sdk/IndexSearchRequest.java, src/main/java/com/meilisearch/sdk/SearchRequest.java, src/test/java/com/meilisearch/integration/SearchTest.java, src/test/java/com/meilisearch/sdk/utils/Movie.java
Fixes #718 
- add showRankingScoreDetails in search
=> Add showRankingScoreDetails in search

.code-samples.meilisearch.yaml, src/main/java/com/meilisearch/sdk/Documents.java, src/main/java/com/meilisearch/sdk/Index.java, src/test/java/com/meilisearch/integration/DocumentsTest.java
Fixes #612 
- allows deletion of documents using a filter
=> Add ability to delete document by filter

.code-samples.meilisearch.yaml, src/main/java/com/meilisearch/sdk/model/MatchingStrategy.java, src/test/java/com/meilisearch/integration/SearchTest.java
Fixes #754 
- Add feature matching strategy
=> Add frequency matching strategy

.code-samples.meilisearch.yaml, src/main/java/com/meilisearch/sdk/IndexSearchRequest.java, src/main/java/com/meilisearch/sdk/Search.java, src/main/java/com/meilisearch/sdk/SearchRequest.java, src/test/java/com/meilisearch/integration/SearchTest.java
Fixes #753 
- Add ranking score threshold
=> Add ranking score threshold

.code-samples.meilisearch.yaml, src/main/java/com/meilisearch/sdk/Client.java, src/main/java/com/meilisearch/sdk/Index.java, src/main/java/com/meilisearch/sdk/SimilarDocumentRequest.java, src/main/java/com/meilisearch/sdk/model/EmbedderInputType.java, src/main/java/com/meilisearch/sdk/model/EmbedderSource.java, src/main/java/com/meilisearch/sdk/model/Embedders.java, src/main/java/com/meilisearch/sdk/model/Settings.java, src/main/java/com/meilisearch/sdk/model/SimilarDocumentsResults.java, src/test/java/com/meilisearch/integration/SearchTest.java, src/test/java/com/meilisearch/integration/classes/AbstractIT.java, src/test/java/com/meilisearch/sdk/utils/Movie.java, src/test/resources/vector_movies.json
Fixes #755
- Add similar documents method to index
=> Add similar documents query to index 

src/test/java/com/meilisearch/integration/SearchTest.java
=> Stabilize vector store usage

README.md
Fixes #759
- Added JDK support section in readme.md
=> Added jdk support section in readme
