.gitignore
README.md
src/main/java/meilisearch/Documents.java
src/main/java/meilisearch/Index.java

The HTTP API for indexing documents takes always a JSON array of documents as a parameter, either if you want to index a single document or a batch. In which case we should probably expose just a single method for both, and rename it in its plural way as `addDocuments(...)` :)
Closes #26

Rename addDocument method to addDocuments

---

src/main/java/com/meilisearch/sdk/Client.java
src/test/java/com/meilisearch/integration/DocumentsTest.java
src/test/java/com/meilisearch/integration/IndexesTest.java

CreateIndex returns Index instance, tested

---

src/main/java/com/meilisearch/sdk/Index.java
src/test/java/com/meilisearch/integration/IndexesTest.java

In current implementation, `getUpdates()` returns an array of UpdateStatus, but `getUpdate()` returns a String containing the server response. This PR makes this behavior consistent, by returning an `UpdateStatus` instance when `getUpdate()` is called

GetUpdate returns a StatusUpdate instance instead of String

---

build.gradle
src/main/java/com/meilisearch/sdk/Config.java
src/main/java/com/meilisearch/sdk/MeiliSearchHttpRequest.java
src/main/java/com/meilisearch/sdk/http/AbstractHttpClient.java
src/main/java/com/meilisearch/sdk/http/ApacheHttpClient.java
src/main/java/com/meilisearch/sdk/http/CustomOkHttpClient.java
src/main/java/com/meilisearch/sdk/http/DefaultHttpClient.java
src/main/java/com/meilisearch/sdk/http/HttpClient.java
src/main/java/com/meilisearch/sdk/http/OkHttpHttpClient.java
src/main/java/com/meilisearch/sdk/http/factory/BasicRequestFactory.java
src/main/java/com/meilisearch/sdk/http/factory/RequestFactory.java
src/main/java/com/meilisearch/sdk/http/request/BasicHttpRequest.java
src/main/java/com/meilisearch/sdk/http/request/HttpMethod.java
src/main/java/com/meilisearch/sdk/http/request/HttpRequest.java
src/main/java/com/meilisearch/sdk/http/response/BasicHttpResponse.java
src/main/java/com/meilisearch/sdk/http/response/HttpResponse.java
src/test/java/com/meilisearch/sdk/http/ApacheHttpClientTest.java
src/test/java/com/meilisearch/sdk/http/CustomOkHttpClientTest.java
src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker

This PR abstracts away everything to do with http requests.
This way we can change the underlying http client without the need for a full rewrite.
Most of the former MeiliSearchHttpRequest class moved into the DefaultHttpClient, turning MeiliSearchHttpRequest into a wrapper to not break existing code.
ApacheHttpClient is a HttpClient basend on the Apache HttpComponents library. I added the Library as a compiletime dependency. This way it doesn't get bundled in the final jar.
RequestFactory is an abstraction to make the request creation more flexible, just in case some special use case needs to overwrite the BasicHttpRequest that is used as a default request class.
Everything combined, the user could change the whole http stack without changes to the sdk code. 
Currently only …

abstract away everything related to http 

---

src/main/java/com/meilisearch/sdk/Client.java
src/main/java/com/meilisearch/sdk/Exceptions/MeiliSearchApiException.java
src/main/java/com/meilisearch/sdk/Exceptions/MeiliSearchCommunicationException.java
src/main/java/com/meilisearch/sdk/Exceptions/MeiliSearchException.java
src/main/java/com/meilisearch/sdk/IndexesHandler.java
src/main/java/com/meilisearch/sdk/MeiliSearchHttpRequest.java
src/main/java/com/meilisearch/sdk/http/DefaultHttpClient.java
src/test/java/com/meilisearch/integration/ClientTest.java
src/test/java/com/meilisearch/integration/DocumentsTest.java
src/test/java/com/meilisearch/integration/ExceptionsTest.java

This PR introduces Custom Exceptions:
MeiliSearchException:
- MeiliSearchApiException => Errors comming from MeiliSearch HTTP API
- MeiliSearchCommunicationException => Erros while unsuccessfully trying to communicate with MeiliSearch
Closes #7

Custom Exceptions: MeiliSearchException => MeiliSearchApiException + MeiliSearchConnectionException

---

gradle/wrapper/gradle-wrapper.properties

Solve compatibility issue:
Error: "Could not initialize class org.codehaus.groovy.runtime.InvokerHelper" on JDK 14
See:
- Gradle issue https://github.com/gradle/gradle/issues/12599
- https://stackoverflow.com/questions/35000729/android-studio-could-not-initialize-class-org-codehaus-groovy-runtime-invokerhel

Upgrade graddle wrapper to gradle 6.3

---

src/main/java/com/meilisearch/sdk/Client.java
src/test/java/com/meilisearch/integration/ClientTest.java

Closes #83 .
Now `updateIndex` returns an instance of Index, and `testUpdateIndexPrimaryKey()` makes sure that this happens.
I was also thinking in including `testUpdateIndexPrimaryKeyIfIndexDoesNotExists()` this test. But I think it's worth having a discussion about it first.
@eskombro and I agree that it should throw a `MeiliSearchApiException`, but what should `updatePrimaryKey` should return when the exception is thrown? Maybe It's worth returning an Optional<Index> for this method?

Refactor update index method

---

src/test/java/com/meilisearch/sdk/json/GsonJsonHandlerTest.java
src/test/java/com/meilisearch/sdk/json/JacksonJsonHandlerTest.java

Closes #72.
In order to remove the warnings from the classes `GsonJsonHandlerTest` and `JacksonJsonHandlerTest`. I implemented a cast in the `.decode()`  methods last parameter (null) to Class<?>[], this is because the method `.decode()` can return a generic, and in that case, the last argument is expecting a list of types to use with a generic.
TBH I don't know if this is the best approach, so in case it's not please let me know.

Remove warnings from Json Handling classes

---

build.gradle

had some problems to get lombok running with intellij 2020.3 due to the version mismatch.

fix lombok version in build.gradle

---

src/test/java/com/meilisearch/integration/SearchTest.java

Closes #15.
In this PR I include to different tests that validate the functionality of place holder search, which consists of making a search a query with an empty string or a null parameter, i.e:
```java
// Both of the following statements return all the documents in the index:
index.search(new SearchRequest(null)); // option 1
index.search(""); // option 2
```
The tests implemented are `testPlaceHolder` and `testPlaceHolderWithLimit`.
I'd appreciate some feedback on the tests because I wasn't sure how atomic the tests should be. If they can be improved in any way, please let me know 😄 !

Add tests for place holder search

---

build.gradle
src/main/java/com/meilisearch/sdk/GenericServiceTemplate.java
src/main/java/com/meilisearch/sdk/ServiceTemplate.java
src/main/java/com/meilisearch/sdk/exceptions/MeiliSearchRuntimeException.java
src/test/java/com/meilisearch/sdk/GenericServiceTemplateTest.java

⚠️ contains the changes of #91 
This PR introduces the "ServiceTemplate". While the HttpClient wraps how http calls are done and the JsonHandler wraps the (de-)serialization logic, the ServiceTemplate defines how these two abstractions work together. 
The GenericServiceTemplate defines the default behaviour for our Implementations. 
Make the Request -> deserialize the response -> return Response

implement ServiceTemplate 

---

build.gradle

that fixes the dependencies.dependency.version missing error when adding our package to a project

add package version to Jupiter

---

src/main/java/com/meilisearch/sdk/GenericServiceTemplate.java
src/main/java/com/meilisearch/sdk/MeiliSearchHttpRequest.java
src/main/java/com/meilisearch/sdk/exceptions/APIError.java
src/main/java/com/meilisearch/sdk/exceptions/MeiliSearchApiException.java
src/main/java/com/meilisearch/sdk/exceptions/MeiliSearchRuntimeException.java
src/test/java/com/meilisearch/integration/ExceptionsTest.java

This PR improves the ErrorHandling of the GenericServiceTemplate. Instead of ignoring an error, we throw it as an RuntimeException. This way the user can decide if he wants to handle it or just ignore it.

improve ErrorHandling

---

src/main/java/com/meilisearch/sdk/MeiliSearchHttpRequest.java
src/main/java/com/meilisearch/sdk/api/documents/DocumentHandler.java
src/main/java/com/meilisearch/sdk/api/documents/SearchRequest.java
src/main/java/com/meilisearch/sdk/api/documents/SearchResponse.java
src/main/java/com/meilisearch/sdk/api/documents/Type.java
src/main/java/com/meilisearch/sdk/api/documents/Update.java
src/main/java/com/meilisearch/sdk/api/index/Index.java
src/main/java/com/meilisearch/sdk/api/index/IndexHandler.java
src/main/java/com/meilisearch/sdk/api/index/Settings.java
src/main/java/com/meilisearch/sdk/api/index/SettingsHandler.java
src/main/java/com/meilisearch/sdk/api/instance/IndexStats.java
src/main/java/com/meilisearch/sdk/api/instance/InstanceHandler.java
src/main/java/com/meilisearch/sdk/api/instance/Stats.java
src/main/java/com/meilisearch/sdk/http/factory/BasicRequestFactory.java
src/main/java/com/meilisearch/sdk/json/JacksonJsonHandler.java
src/test/java/com/meilisearch/integration/ExceptionsTest.java
src/test/java/com/meilisearch/sdk/GenericServiceTemplateTest.java
src/test/java/com/meilisearch/sdk/api/documents/DocumentHandlerTest.java
src/test/java/com/meilisearch/sdk/api/index/IndexHandlerTest.java
src/test/java/com/meilisearch/sdk/api/instance/InstanceHandlerTest.java
src/test/java/com/meilisearch/sdk/http/factory/BasicRequestFactoryTest.java
src/test/java/com/meilisearch/sdk/utils/Movie.java

⚠️ This PR includes #120 
This PR contains the api implementations based on the ServiceTemplate. 
IndexHandler to handle Index and the Settings Endpoints
DocumentHandler to handle Document operations
InstanceHandler to handle Instance-wide endpoints like Stats
DocumentHandler is implemented as a generic to support a user-provided model class.
This way we dont have to return a String.

implement apis based on ServiceTemplate

---

.github/workflows/ossrh-publish.yml
.gitignore
CONTRIBUTING.md
README.md
build.gradle
gradle.properties

Closes #129 
In the build.gradle :
- Update from the deprecated plugin maven to maven-publish
- Signing is now linked to the Publishing task (variables have changed)
- Add nexusStaging task in order to automatize the closing and release in the nexus repository
Other :
- Add github action to publish the package on the Sonatype OSSRH on each release
- gradle.properties has been deleted and we now use environment variables
- Update CONTRIBUTING.md
@curquiza we will need to add the 'Check release validity'
@eskombro do we still need all the publishing steps in the CONTRIBUTING.md?
The last step of the  GitHub Action ossrh-publish.yml has not been tested  "Close and release Nexus Repository" as we don't want to publish a new version yet.
Also the Secrets need to be added.
:blush:

Automatize the package publishment

---

CONTRIBUTING.md
build.gradle

Closes #145 
Update `build.gradle` to be compliant with the maven-publish plugin
It should now create the javadoc and sources that will be checked by Sonatype.
See https://docs.gradle.org/current/userguide/publishing_maven.html

Add javadoc and sources generation

---

README.md

Add the Custom Search With Filters subsection in the Getting Started section of the README to make the users are aware of filtering.
Fixes #259

Add a search example with filter in README

---

src/main/java/com/meilisearch/sdk/exceptions/APIError.java
src/main/java/com/meilisearch/sdk/exceptions/MeiliSearchException.java
src/test/java/com/meilisearch/integration/ExceptionsTest.java

Renamed error Fields:
- errorCode to code
- errorLink to link
- errorType to type
- errorMessage to message
The name of these fields has not been renamed in `UpdateStatus` class because `type` is already used to retrieve the type of the update.

Rename errorCode, errorLink, errorType and errorMessage.

---

src/main/java/com/meilisearch/sdk/Client.java
src/test/java/com/meilisearch/integration/ClientTest.java

All the actions on indexes are now asynchronous, so the methods `delete_if_exist` is now useless.

Remove `deleteIfExist` method

---

src/main/java/com/meilisearch/sdk/Client.java
src/test/java/com/meilisearch/integration/ClientTest.java

All the actions on indexes are now asynchronous, so the methods `get_or_create` is now useless.

Remove getOrCreate method

---

src/main/java/com/meilisearch/sdk/Client.java
src/main/java/com/meilisearch/sdk/GenericServiceTemplate.java
src/main/java/com/meilisearch/sdk/Key.java
src/main/java/com/meilisearch/sdk/KeysHandler.java
src/main/java/com/meilisearch/sdk/MeiliSearchHttpRequest.java
src/main/java/com/meilisearch/sdk/api/documents/Task.java
src/main/java/com/meilisearch/sdk/http/ApacheHttpClient.java
src/main/java/com/meilisearch/sdk/http/CustomOkHttpClient.java
src/main/java/com/meilisearch/sdk/http/DefaultHttpClient.java
src/main/java/com/meilisearch/sdk/http/HttpClient.java
src/main/java/com/meilisearch/sdk/http/request/HttpMethod.java
src/test/java/com/meilisearch/integration/KeysTest.java
src/test/java/com/meilisearch/integration/classes/AbstractIT.java
src/test/java/com/meilisearch/sdk/http/ApacheHttpClientTest.java
src/test/java/com/meilisearch/sdk/http/CustomOkHttpClientTest.java

Granular management of API keys is now added to MeiliSearch. New methods have been created to manage this:
- `http.patch` use by `updateKey`
- `client.getKey` get information about a specific API key.
- `client.createKey` create a new API key.
- `client.deleteKey` delete an API key.
- `client.updateKey` update an API key.
The class HttpURLConnection doesn't accept the PATCH method, I create a workaround and an issue #318

Additions related to API Keys

---

.code-samples.meilisearch.yaml
src/main/java/com/meilisearch/sdk/Client.java
src/main/java/com/meilisearch/sdk/GenericServiceTemplate.java
src/main/java/com/meilisearch/sdk/KeysHandler.java
src/main/java/com/meilisearch/sdk/MeiliSearchHttpRequest.java
src/main/java/com/meilisearch/sdk/http/ApacheHttpClient.java
src/main/java/com/meilisearch/sdk/http/CustomOkHttpClient.java
src/main/java/com/meilisearch/sdk/http/DefaultHttpClient.java
src/main/java/com/meilisearch/sdk/http/HttpClient.java
src/main/java/com/meilisearch/sdk/http/request/HttpMethod.java
src/test/java/com/meilisearch/integration/KeysTest.java
src/test/java/com/meilisearch/sdk/http/ApacheHttpClientTest.java
src/test/java/com/meilisearch/sdk/http/CustomOkHttpClientTest.java

The HTTP `PATCH` method has just been introduced in `Meilisearch` following the release of v0.25.0.
This method should be used in the new `updateKey()` method but it didn't pass the `CI` test so this method has been removed.
See #318

Remove updateKeys due to PATCH http method

---

src/main/java/com/meilisearch/sdk/Details.java
src/main/java/com/meilisearch/sdk/Task.java
src/test/java/com/meilisearch/integration/TasksTest.java

Fixes #331
Created new Details class and added the Details field to Task class
- [ x ] Does this PR fix an existing issue?
- [ x ] Have you read the contributing guidelines?
- [ x ] Have you made sure that the title is accurate and descriptive of the changes?
Thank you so much for contributing to MeiliSearch!

Create new Details class and add Details field in Task class

---

src/test/java/com/meilisearch/integration/SearchTest.java

Changes in the request result of a search query due to a new implementation of `typo-tolerance`.
Until now `typo` on the first letter is now counting as 2 typos

Fix test due to changes v0.27.0

---

src/main/java/com/meilisearch/sdk/Search.java
src/main/java/com/meilisearch/sdk/SearchRequest.java
src/main/java/com/meilisearch/sdk/api/documents/SearchRequest.java
src/test/java/com/meilisearch/integration/SearchTest.java
src/test/java/com/meilisearch/sdk/SearchRequestTest.java

As per https://github.com/meilisearch/meilisearch/issues/2214 new search parameters are introduced: 
- `highlightPreTag`
- `highlightPostTag`
- `cropMarker`

Add new search parameters highlightPreTag, highlightPostTag and cropMarker

---

src/test/java/com/meilisearch/integration/SearchNestedTest.java
src/test/java/com/meilisearch/integration/classes/AbstractIT.java

Add tests on nested fields to ensure it is still maintained in Meilisearch.

Ensure nested field support

---

build.gradle

This version makes this package compatible with MeiliSearch v0.27.0🎉 
Check out the changelog of [MeiliSearch v0.27.0](https://github.com/meilisearch/MeiliSearch/releases/tag/v0.27.0) for more information about the changes.
- Ensure nested field support #374 @alallema
- Add new search parameters `highlightPreTag`, `highlightPostTag` and `cropMarker` #375 @alallema

Update version for the next release (v0.7.2)

---

src/main/java/com/meilisearch/sdk/Config.java
src/main/java/com/meilisearch/sdk/Details.java
src/main/java/com/meilisearch/sdk/Dump.java
src/main/java/com/meilisearch/sdk/GenericServiceTemplate.java
src/main/java/com/meilisearch/sdk/Key.java
src/main/java/com/meilisearch/sdk/Result.java
src/main/java/com/meilisearch/sdk/SearchRequest.java
src/main/java/com/meilisearch/sdk/Settings.java
src/main/java/com/meilisearch/sdk/Task.java
src/main/java/com/meilisearch/sdk/TaskError.java
src/main/java/com/meilisearch/sdk/TenantTokenOptions.java
src/main/java/com/meilisearch/sdk/api/documents/SearchRequest.java
src/main/java/com/meilisearch/sdk/api/documents/SearchResponse.java
src/main/java/com/meilisearch/sdk/api/documents/Task.java
src/main/java/com/meilisearch/sdk/api/index/Index.java
src/main/java/com/meilisearch/sdk/api/index/Settings.java
src/main/java/com/meilisearch/sdk/api/instance/IndexStats.java
src/main/java/com/meilisearch/sdk/api/instance/Stats.java
src/main/java/com/meilisearch/sdk/http/request/BasicHttpRequest.java
src/main/java/com/meilisearch/sdk/http/response/BasicHttpResponse.java
src/main/java/com/meilisearch/sdk/model/SearchResult.java

Fixes #<379>
[issue link] (https://github.com/meilisearch/meilisearch-java/issues/379)

replaced traditional getter setter with lombok getter setter

---

.gitignore
build.gradle

Add a tool to show the current status of the test coverage.
There is no specific command to run, just running the tests command from `gradlew`: `./gradlew test integrationTest` and check the report in the `tmp/` folder in the project path.

Add code-coverage tool (jacoco)

---

src/main/java/com/meilisearch/sdk/SearchRequest.java
src/test/java/com/meilisearch/sdk/SearchRequestTest.java

Add a method that returns the JSON String of the SearchRequest

Add toString method to SearchRequest Class

---

src/main/java/com/meilisearch/sdk/Client.java
src/main/java/com/meilisearch/sdk/Documents.java
src/main/java/com/meilisearch/sdk/HttpClient.java
src/main/java/com/meilisearch/sdk/IndexesHandler.java
src/main/java/com/meilisearch/sdk/KeysHandler.java
src/main/java/com/meilisearch/sdk/Search.java
src/main/java/com/meilisearch/sdk/SettingsHandler.java

Most of the methods had to use the `jsonHandler` after the call to the `post` method through the client. The purpose of this PR is to bypass this step to simplify the call to the `post` method via the client:
```java
public Task updateRankingRuleSettings(String uid, String[] rankingRules)
throws MeilisearchException {
return httpClient.jsonHandler.decode(
httpClient.post(
"/indexes/" + uid + "/settings/ranking-rules",
rankingRules == null
? httpClient.jsonHandler.encode(rankingRules)
: rankingRules),
Task.class);
}
```
became:
```java
public Task updateRankingRuleSettings(String uid, String[] rankingRules)
throws MeilisearchException {
String urlPath = "/indexes/" + uid + "/settings/ranking-rules";
return httpClient.post(
urlPath,
rankingRules == null ? …
```

Provide a generic to http post methods 

---

src/main/java/com/meilisearch/sdk/Client.java
src/main/java/com/meilisearch/sdk/Documents.java
src/main/java/com/meilisearch/sdk/HttpClient.java
src/main/java/com/meilisearch/sdk/IndexesHandler.java

Most of the methods had to use the `jsonHandler` after the call to the `put` method through the client. The purpose of this PR is to bypass this step to simplify the call to the `put` method via the client:
```java
Task updateDocuments(String uid, String document)
throws MeilisearchException {
String urlPath = "/indexes/" + uid + "/documents";
Task task = httpClient.jsonHandler.decode(httpClient.put(urlPath, document), Task.class);
return task;
}
```
became
```java
Task updateDocuments(String uid, String document)
throws MeilisearchException {
String urlPath = "/indexes/" + uid + "/documents";
return httpClient.put(urlPath, document, Task.class);
}
```

Provide a generic to http put method

---

src/main/java/com/meilisearch/sdk/Client.java
src/main/java/com/meilisearch/sdk/Documents.java
src/main/java/com/meilisearch/sdk/HttpClient.java
src/main/java/com/meilisearch/sdk/IndexesHandler.java
src/main/java/com/meilisearch/sdk/KeysHandler.java
src/main/java/com/meilisearch/sdk/SettingsHandler.java

Most of the methods had to use the `jsonHandler` after the call to the `delete` method through the client. The purpose of this PR is to bypass this step to simplify the call to the `delete` method via the client:
```java
public Task resetRankingRulesSettings(String uid) throws MeilisearchException {
Task task = jsonHandler.decode(this.indexesHandler.delete(uid), Task.class);
return task;
}
```
became
```java
public Task resetRankingRulesSettings(String uid) throws MeilisearchException {
String urlPath = "/indexes/" + uid + "/settings/ranking-rules";
return httpClient.delete(urlPath, Task.class);
}
```

Provide a generic to http delete method

---

src/main/java/com/meilisearch/sdk/Client.java
src/main/java/com/meilisearch/sdk/Documents.java
src/main/java/com/meilisearch/sdk/HttpClient.java
src/main/java/com/meilisearch/sdk/Index.java
src/main/java/com/meilisearch/sdk/IndexesHandler.java
src/main/java/com/meilisearch/sdk/KeysHandler.java
src/main/java/com/meilisearch/sdk/Search.java
src/main/java/com/meilisearch/sdk/SettingsHandler.java
src/main/java/com/meilisearch/sdk/TasksHandler.java
src/main/java/com/meilisearch/sdk/http/CustomOkHttpClient.java
src/main/java/com/meilisearch/sdk/http/response/BasicResponse.java
src/main/java/com/meilisearch/sdk/http/response/HttpResponse.java
src/main/java/com/meilisearch/sdk/json/GsonJsonHandler.java

Most of the methods had to use the `jsonHandler` after the call to the `get` method through the client. The purpose of this PR is to bypass this step to simplify the call to the get method via the client:
```java
public String[] getRankingRuleSettings(String uid) throws MeilisearchException {
String urlPath = "/indexes/" + uid + "/settings/synonyms";
return httpClient.jsonHandler.decode(httpClient.get(urlPath, String.class), String[].class);
}
```
became
```java
public String[] getRankingRuleSettings(String uid) throws MeilisearchException {
String urlPath = "/indexes/" + uid + "/settings/ranking-rules";
return httpClient.get(urlPath, String[].class);
}
```
**Note:**
This method still need a call to the `decode` method from `jsonHandler`
```java
public Map<String, String[]> …
```

Provide a generic to http get methods

---

src/main/java/com/meilisearch/sdk/HttpClient.java
src/main/java/com/meilisearch/sdk/http/CustomOkHttpClient.java
src/main/java/com/meilisearch/sdk/http/request/HttpMethod.java
src/test/java/com/meilisearch/sdk/http/CustomOkHttpClientTest.java

Fixes #334
This PR add the `patch` `HTTP` method to the `HttpClient` Class.

Add patch http method and tests

---

src/main/java/com/meilisearch/sdk/Client.java
src/main/java/com/meilisearch/sdk/HttpClient.java
src/main/java/com/meilisearch/sdk/Index.java
src/main/java/com/meilisearch/sdk/InstanceHandler.java
src/test/java/com/meilisearch/integration/InstanceTest.java

Add missing method:
- `health()`
- `isHealthy()`
- `getVersion()`
- `getStats()`
- `index.getStats()`

Add few missing method

---

.code-samples.meilisearch.yaml
README.md
build.gradle

This version includes a major redesign of the SDK. ([#425](https://github.com/meilisearch/meilisearch-java/pull/425)) [@alallema](https://github.com/alallema)
* Redesign of the client (#449) @alallema:
* Use `OkHttp` library by default for the Meilisearch client
* No interface for the creation of a Client disappearing of the class `GenericServiceTemplate`, `ServiceTemplate`, `AbstractClient`, `ApacheClient`, and `DefaultHttpClient`.
* Rename `getAllIndexes` method in `getIndexes` (#477) @alallema
* All parameters of the managers accessible in the client are now private: `Config`, `IndexesHandler`, `InstanceHandler`, ` TasksHandler`, `KeysHandler`, `JsonHandler`.
* Factories for the answer and the response disappeared, those classes were removed: `BasicRequestFactory`, `BasicHttpResponse`, …

Update version for the next release (v0.8.0)

---

src/main/java/com/meilisearch/sdk/IndexesHandler.java
src/main/java/com/meilisearch/sdk/SettingsHandler.java

Breaking because enforces the users to use Meilisearch v0.28.0
- `PATCH` `/indexes/{indexUid}` instead of `PUT`
- `PATCH` `/indexes/{indexUid}/settings` instead of `POST`
- `PATCH` `/indexes/{indexUid}/settings/typo-tolerance` instead of `POST`
- `PUT` `/indexes/{indexUid}/settings/displayed-attributes` instead of `POST`
- `PUT` `/indexes/{indexUid}/settings/distinct-attribute` instead of `POST`
- `PUT` `/indexes/{indexUid}/settings/filterable-attributes` instead of `POST`
- `PUT` `/indexes/{indexUid}/settings/ranking-rules` instead of `POST`
- `PUT` `/indexes/{indexUid}/settings/searchable-attributes` instead of `POST`
- `PUT` `/indexes/{indexUid}/settings/stop-words` instead of `POST`
- `PUT` `/indexes/{indexUid}/settings/synonyms` instead of `POST`

Change HTTP methods

---

src/main/java/com/meilisearch/sdk/Search.java
src/main/java/com/meilisearch/sdk/SearchRequest.java
src/main/java/com/meilisearch/sdk/model/SearchResult.java
src/test/java/com/meilisearch/integration/SearchNestedTest.java
src/test/java/com/meilisearch/integration/SearchTest.java
src/test/java/com/meilisearch/sdk/SearchRequestTest.java
src/test/java/com/meilisearch/sdk/utils/Movie.java

- Rename `nbHits` response parameter to `estimatedTotalHits`.
- Delete `exhaustiveNbHits` response parameter.
- Delete `exhaustiveFacetsCount` response parameter.
- `matches` request parameter is renamed `showMatchesPosition`.
- `facetsDistribution` request parameter is renamed `facets`.
- `facetsDistribution` response parameter is renamed `facetDistribution`.

Apply search changes

---

.github/workflows/pre-release-tests.yml

Following the update of `setup-java` to v3 the distribution is now required.
It's throw an [error](https://github.com/meilisearch/meilisearch-java/actions/runs/3788961009/jobs/6442255873)
```
Run actions/setup-java@v3
with:
java-version: 1.8
java-package: jdk
check-latest: false
server-id: github
server-username: GITHUB_ACTOR
server-password: GITHUB_TOKEN
overwrite-settings: true
job-status: success
token: ***
Error: Input required and not supplied: distribution
```

Modify setup-java in ci workflow for v3

---

.code-samples.meilisearch.yaml
src/main/java/com/meilisearch/sdk/Client.java
src/test/java/com/meilisearch/integration/ClientTest.java

Related to: https://github.com/meilisearch/integration-guides/issues/205
Breaking because enforces the users to use Meilisearch v0.28.0

Apply dumps changes

---

src/main/java/com/meilisearch/sdk/Client.java
src/main/java/com/meilisearch/sdk/IndexesHandler.java
src/main/java/com/meilisearch/sdk/TasksHandler.java
src/main/java/com/meilisearch/sdk/model/IndexesQuery.java
src/test/java/com/meilisearch/integration/ClientTest.java
src/test/java/com/meilisearch/integration/classes/AbstractIT.java

Related to: https://github.com/meilisearch/meilisearch/issues/2373
```java
client.getIndexes()
```
returns for example
```bash
com.meilisearch.sdk.model.Results@2a742aa2
```
```java
client.getRawIndexes()
```
returns for example
```bash
{"results":[],"offset":0,"limit":20,"total":0}
```

Update Index API for Meilisearch v.28

---

src/main/java/com/meilisearch/sdk/Documents.java
src/main/java/com/meilisearch/sdk/Index.java
src/main/java/com/meilisearch/sdk/model/DocumentsQuery.java
src/test/java/com/meilisearch/integration/DocumentsTest.java

Related to: https://github.com/meilisearch/integration-guides/issues/205
Breaking because enforces the users to use Meilisearch v0.28.0
- `GET /documents/:uid`, `GET /documents` Add the possibility to reduce the body payload by using a query parameter called `fields` (previously called `attributesToRetrieve`), check the issue and the spec for the entire behavior.
- The documents objects now return wrap in a `Results`
- Create two separate methods for `GET /documents`:
- `<T> Results<T> getDocuments(Class<T> targetClass) throws MeilisearchException` -> return an `Object`
- `String getRawDocuments()` -> return a `String`
- Create two separate methods for `GET /documents/:uid`:
- `<T> Results<T> getDocument(String identifier, Class<T> targetClass) throws MeilisearchException` -> return an …

Update documents API for Meilisearch v.28

---

src/main/java/com/meilisearch/sdk/Documents.java
src/main/java/com/meilisearch/sdk/Index.java
src/main/java/com/meilisearch/sdk/IndexesHandler.java
src/main/java/com/meilisearch/sdk/InstanceHandler.java
src/main/java/com/meilisearch/sdk/KeysHandler.java
src/main/java/com/meilisearch/sdk/SettingsHandler.java
src/main/java/com/meilisearch/sdk/TasksHandler.java
src/main/java/com/meilisearch/sdk/http/URLBuilder.java
src/main/java/com/meilisearch/sdk/model/DocumentQuery.java
src/main/java/com/meilisearch/sdk/model/DocumentsQuery.java
src/main/java/com/meilisearch/sdk/model/IndexesQuery.java
src/main/java/com/meilisearch/sdk/model/KeysQuery.java
src/main/java/com/meilisearch/sdk/model/TasksQuery.java

- Creation of the class `DocumentQuery` to getting one document.
**Notes:**
- A function has been created in each handler to avoid instantiating a single `new URLBuilder()` in the class parameters.

Refactor handlers for the usage of URLBuilder

---

.code-samples.meilisearch.yaml
README.md
build.gradle
src/main/java/com/meilisearch/sdk/Version.java

- `SearchQuery` changes (#505) @alallema
- Renamed `facetsDistribution` field to `facets`
- Renamed `matches` field to `showMatchesPosition`
- `SearchResult` changes (#505) @alallema
- Renamed `nbHits ` field to `estimatedTotalHits`
- Removed `exhaustiveFacetsCount` field
- Removed `exhaustiveNbHits` field
- Renamed `Result` class to plural `Results` (#508) @alallema 
- Remove method `client.getDumpStatus` (#515) @alallema
- Method `client.createDump` now returns a `TaskInfo` object (#515) @alallema
- `client.getTasks()` now returns a `TasksResults` (#517) @alallema
- `client.getIndexes()` now returns a `Results<Index>` (#516) @alallema 
- `client.getRawIndexes()` method return a String (#516) @alallema 
- `client.getKeys()` now returns a `Results<Key>` (#517) @alallema
- …

Update version for the next release (v0.9.0)

---

.code-samples.meilisearch.yaml
src/main/java/com/meilisearch/sdk/Index.java
src/main/java/com/meilisearch/sdk/SettingsHandler.java
src/test/java/com/meilisearch/integration/SettingsTest.java

Fixes #525 
- Correction of naming methods related to Ranking Rules

Correction of naming methods related to Ranking Rules

---

.code-samples.meilisearch.yaml
README.md
build.gradle
src/main/java/com/meilisearch/sdk/Version.java

Check out the changelog of [Meilisearch v0.29.0](https://github.com/meilisearch/meilisearch/releases/tag/v0.29.0) for more information on the changes.
This breaking change *__may not affect you__*, but in any case, you should check your search queries if you want to keep the same behavior from `v0.28`.
* The `NOT` filter keyword does not have an implicitly `EXIST` operator anymore. Check out for more information: https://github.com/meilisearch/meilisearch/issues/2486
* Correction of naming methods related to Ranking Rules (https://github.com/meilisearch/meilisearch-java/pull/539) @ghousek1
* Ensure support to the new search query parameter `MatchingStrategy` (#434) @alallema
* Ensure support to keys with wildcarded actions.
- `actions` field during key creation now accepts wildcards on …

Update version for the next release (v0.10.0)

---

src/main/java/com/meilisearch/sdk/Search.java
src/main/java/com/meilisearch/sdk/SearchRequest.java
src/test/java/com/meilisearch/integration/SearchNestedTest.java
src/test/java/com/meilisearch/integration/SearchTest.java
src/test/java/com/meilisearch/sdk/SearchRequestTest.java

The `SearchRequest` class has been modified to simplify its use, see #455
- Removing all the constructors with multiple arguments on the Class
- Add the possibility to use a `builder()`
```
SearchRequest.builder()
.q("")
.offset(10)
.limit(200)
.cropLength(5)
.cropMarker("…")
.build();
```
- Keep the possibility to initialize the Class like:
```
new SearchRequest("")
.setOffset(10)
.setLimit(200)
.setCropLength(5)
.setCropMarker("…");
```

Add a builder for SearchRequest class

---

src/main/java/com/meilisearch/sdk/Client.java
src/main/java/com/meilisearch/sdk/TasksHandler.java
src/main/java/com/meilisearch/sdk/model/CancelTasksQuery.java
src/main/java/com/meilisearch/sdk/model/DeleteTasksQuery.java
src/test/java/com/meilisearch/integration/TasksTest.java

Add the cancel task api see spec:  https://github.com/meilisearch/specifications/pull/195
- params: `CancelTasksQuery`
- returns: `TaskInfo`

Add cancel task api for v0.30.0

---

src/main/java/com/meilisearch/sdk/model/Faceting.java
src/main/java/com/meilisearch/sdk/model/Pagination.java
src/main/java/com/meilisearch/sdk/model/TaskDetails.java
src/main/java/com/meilisearch/sdk/model/TaskInfo.java

V0.30.0
in TasksInfo:
in TaskDetais:
Creation of the `Pagination` and the `Faceting` class.

Update TaskDetails and TaskInfo for v0.30.0

---

README.md
src/main/java/com/meilisearch/sdk/Config.java

Fixes #550
-  added more constructors to support JsonHandler
- API stays backwards compatible

Fix: #550 added constructor to initialize HttpClient using Gson by default

---

src/main/java/com/meilisearch/sdk/TasksHandler.java
src/main/java/com/meilisearch/sdk/http/URLBuilder.java
src/main/java/com/meilisearch/sdk/model/TasksQuery.java
src/test/java/com/meilisearch/integration/TasksTest.java
src/test/java/com/meilisearch/sdk/TaskHandlerUtilsTest.java
src/test/java/com/meilisearch/sdk/http/URLBuilderTest.java

Add new filters on the `get /tasks` route.
Present in this [spec](https://github.com/meilisearch/specifications/pull/195)
V0.30.0
in TasksQuery:
Tests:

Add tasks filters for v0.30

---

src/main/java/com/meilisearch/sdk/Client.java
src/main/java/com/meilisearch/sdk/model/SwapIndexesParams.java
src/main/java/com/meilisearch/sdk/model/TaskDetails.java
src/test/java/com/meilisearch/integration/ClientTest.java

As [per the specification](https://github.com/meilisearch/specifications/pull/192)
- params: TasksQuery
- returns: TaskInfo

Add swap indexes api for v0.30.0

---

src/main/java/com/meilisearch/sdk/Client.java
src/main/java/com/meilisearch/sdk/IndexesHandler.java
src/test/java/com/meilisearch/integration/ClientTest.java

Fixes #521 
- Implement overload method on getRawIndexes for accepting query parameters
- Add test for getRawIndexes with params

Implement `getRawIndexes` with query parameters

---

src/main/java/com/meilisearch/sdk/Search.java
src/test/java/com/meilisearch/integration/SearchTest.java

This PR corrects the use of the `matchingStrategy` enum which sends `all` and `last` in upper case instead of lower case.

Fix matching strategy enum usage and add test

---

.code-samples.meilisearch.yaml
src/test/java/com/meilisearch/integration/SearchTest.java
src/test/java/com/meilisearch/sdk/SearchRequestTest.java

Changed SearchRequest initializations to builder insted of a constructor
- Changed code-samples.meilisearch.yaml file, SearchRequestTest file and SearchTest file
Fixes #<560
-  Changed SearchRequest initializations to builder insted of a constructor
- [x ] Does this PR fix an existing issue, or have you listed the changes applied in the PR description (and why they are needed)?
- [ x] Have you read the contributing guidelines?
- [ x] Have you made sure that the title is accurate and descriptive of the changes?

Changed `SearchRequest` initializations to builder in code-sample

---

src/main/java/com/meilisearch/sdk/Index.java
src/main/java/com/meilisearch/sdk/SettingsHandler.java
src/main/java/com/meilisearch/sdk/model/Settings.java
src/test/java/com/meilisearch/integration/SettingsTest.java

Fixes #411 
- Add the new methods to customize pagination
-GET /indexes/:index_uid/settings/pagination
-PATCH /indexes/:index_uid/settings/pagination
-DELETE /indexes/:index_uid/settings/pagination
- Add tests

Add support to the pagination setting customization at the index level

---

README.md
build.gradle

Since the reported error is just a misconfiguration, I believe we can fix it by always making the lib required since that's true after the refactor #425.
Fix #580

Add explicitly requirement of okhttp

---

src/test/java/com/meilisearch/integration/ClientTest.java
src/test/java/com/meilisearch/integration/DocumentsTest.java
src/test/java/com/meilisearch/integration/ExceptionsTest.java
src/test/java/com/meilisearch/integration/InstanceTest.java
src/test/java/com/meilisearch/integration/KeysTest.java
src/test/java/com/meilisearch/integration/SearchNestedTest.java
src/test/java/com/meilisearch/integration/SearchTest.java
src/test/java/com/meilisearch/integration/SettingsTest.java
src/test/java/com/meilisearch/integration/TasksTest.java
src/test/java/com/meilisearch/integration/TenantTokenTest.java
src/test/java/com/meilisearch/sdk/SearchRequestTest.java
src/test/java/com/meilisearch/sdk/TaskHandlerUtilsTest.java
src/test/java/com/meilisearch/sdk/exceptions/MeilisearchApiExceptionTest.java
src/test/java/com/meilisearch/sdk/exceptions/MeilisearchCommunicationExceptionTest.java
src/test/java/com/meilisearch/sdk/exceptions/MeilisearchExceptionTest.java
src/test/java/com/meilisearch/sdk/exceptions/MeilisearchTimeoutExceptionTest.java
src/test/java/com/meilisearch/sdk/http/BasicRequestTest.java
src/test/java/com/meilisearch/sdk/http/BasicResponseTest.java
src/test/java/com/meilisearch/sdk/http/URLBuilderTest.java
src/test/java/com/meilisearch/sdk/json/GsonJsonHandlerTest.java
src/test/java/com/meilisearch/sdk/json/JacksonJsonHandlerTest.java

Apologies for the enormous PR!
Fixes #324
- Converts existing tests to use Hamcrest matchers where possible (it still uses JUnit for `assertThrows` and `assertDoesNotThrow`)
- Removes some unnecessary casts and other small tweaks to the tests here and there

Update tests to use Hamcrest matchers instead of JUnit assertions 

---

.code-samples.meilisearch.yaml

I created [scripts to manage code samples](https://github.com/meilisearch/integration-automations/pull/164) (internal only)
1. I found out the following code samples are still in this repo but not used by the documentation anymore, so I removed them:
```bash
meilisearch-java
- 'delete_documents_1' not found in documentation
- 'get_all_tasks_filtering_1' not found in documentation
- 'get_all_tasks_filtering_2' not found in documentation
- 'search_parameter_guide_matches_1' not found in documentation
- 'documents_guide_add_movie_1' not found in documentation
- 'getting_started_communicating_with_a_protected_instance' not found in documentation
- 'faceted_search_facets_1' not found in documentation
```
2. I found the following code samples were missing:
```bash
meilisearch-java
- …
```

Remove useless code samples and add missing ones

---

src/main/java/com/meilisearch/sdk/Index.java
src/test/java/com/meilisearch/integration/ClientTest.java

Fixes #655
Gson has issues working with the class `com.meilisearch.sdk.Index` in Java 9 and higher. Specifically all the fields which hold a `com.meilisearch.sdk.HttpClient`. Marking those fields as `transient` excludes them from serialization and thus preventing the reflective access on JDK-internal types.

Mark internal fields as transient

---

.github/workflows/ossrh-publish.yml
build.gradle

Fixes #654 
Replaces the deprecated Gradle Publish Plugin with a new one.
Requires additional testing as I do not possess a Sonatype Account.

Replace deprecated publish plugin

---

src/main/java/com/meilisearch/sdk/exceptions/MeilisearchException.java

Fixes #677
- Change `MeilisearchException` to extends `RuntimeException`.

Make MeilisearchException a RuntimeException

---

.code-samples.meilisearch.yaml
src/main/java/com/meilisearch/sdk/Index.java
src/main/java/com/meilisearch/sdk/SettingsHandler.java
src/main/java/com/meilisearch/sdk/model/Settings.java
src/test/java/com/meilisearch/integration/SettingsTest.java
src/test/java/com/meilisearch/sdk/SettingsHandlerTest.java

Fixes #660
- Add a new setting as dictionary and get, update, reset methods for this setting 

Support user-dictionary loading #660

---

src/main/java/com/meilisearch/sdk/json/GsonJsonHandler.java
src/main/java/com/meilisearch/sdk/json/GsonKeyTypeAdapter.java
src/main/java/com/meilisearch/sdk/model/Key.java
src/test/java/com/meilisearch/sdk/json/GsonJsonHandlerTest.java

Fixes #487
- Removes Key specific logic from `GsonJsonHandler` in favour of creating a type adapter for serializing and deserializing `Key`
- Removes a constructor in `GsonJsonHandler` which seemingly is only used for testing (a _spy_ was created in one of the unit tests, recording actions taken - this unit test has been updated). This specific constructor allowed a `Gson` instance to be passed in, which would allow bypassing the addition of the type adapter, which would break the `Key` specific functionality just added.
Depending on how you view this, it could be seen as a breaking change, if you consider the `GsonJsonHandler` to be part of the public API. However, I would argue that it should not be and I don't see another way (though I may well be wrong) to feasibly move the `Key` …

Improve GSON JSON handler, moving Key specific logic

---

src/main/java/com/meilisearch/sdk/model/Pagination.java
src/test/java/com/meilisearch/integration/SettingsTest.java

This is a tiny PR to make the Pagination initial more easier.
The current implementation make extra lines to config Pagination. Here is an example:
**Before**
```Kotlin
val index = meilisearchClient.index(it.getIndex())
val defaultPagination = Pagination()
defaultPagination.maxTotalHits = 5000
index.updatePaginationSettings(defaultPagination)
```
**After**
```Kotlin
val index = meilisearchClient.index(it.getIndex())
index.updatePaginationSettings(Pagination(5000))
```

Add all-args-constructor for easy initial config Pagination

---

.github/workflows/ossrh-publish.yml

Fixes https://github.com/meilisearch/meilisearch-java/issues/704
- Remove the test task from the build task since we already ran the tests. On the main, there is no need to test execution further.
- For some reason there is a test now that requires meilisearch to run (which was not the case before)

Ignore tests when running gradle build on releasing

---

.code-samples.meilisearch.yaml
src/main/java/com/meilisearch/sdk/Documents.java
src/main/java/com/meilisearch/sdk/model/DocumentsQuery.java
src/test/java/com/meilisearch/integration/DocumentsTest.java

Fixes #613
- Add support to get documents by filter.
- Updatex code samples.

Add support to get documents by filter

---

src/main/java/com/meilisearch/sdk/Documents.java
src/main/java/com/meilisearch/sdk/Index.java
src/test/java/com/meilisearch/integration/DocumentsTest.java

Addresses #590 
- Includes csvDelimiter parameter in the addDocuments method
- Includes csvDelimiter parameter in the updateDocuments method
- Tests are not included because there are some clarifications that we require to verify if the issue is already partially/completely implemented. After adding the csvDelimiter to each method, we researched adding a custom csv delimiter in Java and found no built-in support. Would this be best completed by utilizing an external library like OpenCSV? 
- This PR addresses the function parameter additions to support a custom csvDelimiter if necessary but does not adequately test the functionality of these additions. 
- It is unclear from the issue if this is already implemented, this would address the first subtask for #590 if the issue has not been …

Custom csv delimiter

---

.code-samples.meilisearch.yaml
src/main/java/com/meilisearch/sdk/FacetSearch.java
src/main/java/com/meilisearch/sdk/FacetSearchRequest.java
src/main/java/com/meilisearch/sdk/Index.java
src/main/java/com/meilisearch/sdk/model/FacetSearchResult.java
src/main/java/com/meilisearch/sdk/model/FacetSearchable.java

Fixes #635 
- implement facet search

Add facet search support

---

src/main/java/com/meilisearch/sdk/json/GsonJsonHandler.java
src/main/java/com/meilisearch/sdk/json/JacksonJsonHandler.java
src/main/java/com/meilisearch/sdk/json/JsonHandler.java

Refactor #737
The targetClass parameter should be of type Class<T>, not Class<?>. This provides stronger type safety because you can check the type of T at compile time rather than at run time

Adjust the targetClass parameter variable of the decode method in JsonHandler from class<?> to class<T>

---

.code-samples.meilisearch.yaml
src/main/java/com/meilisearch/sdk/model/FacetSortValue.java
src/main/java/com/meilisearch/sdk/model/Faceting.java
src/test/java/com/meilisearch/integration/SettingsTest.java

Fixes #634 
- added feature to sort facets value by alphanumerical or count order

Add sort facets value feature

---

src/main/java/com/meilisearch/sdk/model/Task.java
src/main/java/com/meilisearch/sdk/model/TaskError.java
src/test/java/com/meilisearch/integration/ExceptionsTest.java
src/test/java/com/meilisearch/integration/TasksTest.java

Seems like the `TaskError` object is only returning empty Strings when trying to get the error details of a task. Seems to be a missmatch between the field naming, and number of fields based on the API response. Therefor it dosent understand what to map, and only gives empty strings back.
None
- It moves the `TaskError` class to the `model` package, closer to the usage in `Task` class.
- Since its peers`TaskDetails`, and `TaskStatus` are already here.
- Updates the field in `TaskError` to match the API naming, and number of fields.
- Updates the Exception integration test to use the correct naming and import.
- Adds Integration tests to check that `TaskError` fields is not blank or null.

Fixing empty TaskError response

---

src/main/java/com/meilisearch/sdk/HttpClient.java

Fixes #764
- throw MeilisearchApiException on response codes >= 400 when using patch method in httpclient

Fix Update settings api failure throws ClassCastException

---

src/main/java/com/meilisearch/sdk/Client.java
src/main/java/com/meilisearch/sdk/FederationOptions.java
src/main/java/com/meilisearch/sdk/IndexSearchRequest.java
src/main/java/com/meilisearch/sdk/MultiSearchFederation.java
src/main/java/com/meilisearch/sdk/MultiSearchRequest.java
src/test/java/com/meilisearch/integration/SearchTest.java

Fixes #768
- Adds a new parameter federation to the multiSearch method.
- Introduces a new search parameter federationOptions to the search query.
- Adds a getter method to the MultiSearchRequest class to retrieve the query list for creating the payload.
- Adds a test to validate the new functionality.

Add Federation Parameter to multisearch method

---

src/main/java/com/meilisearch/sdk/IndexSearchRequest.java

PARAMETER
“Fixes #<issue_number>”
- ...When I use Non-federated multi-search, I find that I can't add attributesToSearchOn, I'm sure there is no this parameter in IndexSearchRequest.I added one attributesToSearchOn.

Add attributesToSearchOn to IndexSearchRequest

---

src/main/java/com/meilisearch/sdk/MergeFacets.java
src/main/java/com/meilisearch/sdk/MultiSearchFederation.java
src/main/java/com/meilisearch/sdk/MultiSearchRequest.java
src/main/java/com/meilisearch/sdk/model/FacetsByIndexInfo.java
src/main/java/com/meilisearch/sdk/model/MultiSearchResult.java
src/test/java/com/meilisearch/integration/SearchTest.java
src/test/java/com/meilisearch/integration/TenantTokenTest.java
src/test/resources/movies.json

Fixes #787 
- Adds support for `federation.facetsByIndex` in the `POST /multi-search` route.
- Allows for merging of returned facets with `federation.mergeFacets` in the `POST /multi-search` route

Support facet distribution for federated search

---

README.md

- Updates the README example code to show the necessity to cast the returned value (new `Searchable` interface) to `SearchResult`
- Adds a new comprehensive example demonstrating custom search with pagination
- Shows practical usage of pagination parameters like `setPage()` and `setHitsPerPage()`
- Includes example JSON response showing pagination metadata (totalPages, hitsPerPage, etc.)

docs: update README with SDK changes and add pagination examples

---

src/main/java/com/meilisearch/sdk/http/URLBuilder.java
src/main/java/com/meilisearch/sdk/model/TasksQuery.java
src/test/java/com/meilisearch/integration/TasksTest.java
src/test/java/com/meilisearch/sdk/http/URLBuilderTest.java

Fixes #798 
- Accepts 'reverse' field to provider ordering flexibility
- [ Y ] Does this PR fix an existing issue, or have you listed the changes applied in the PR description (and why they are needed)?
- [ Y ] Have you read the contributing guidelines?
- [ Y ] Have you made sure that the title is accurate and descriptive of the changes?

Add Reverse ordering support for Task API

---

src/main/java/com/meilisearch/sdk/model/IndexStats.java
src/main/java/com/meilisearch/sdk/model/Stats.java

Fixes #819 #820 #821 
- Adds `usedDatabaseSize` to stats
- Adds documents database metrics to stats
- Adds embbedings database metrics to stats

Add usedDatabaseSize to stats, document and embeddings database metrics to index stats

---

src/main/java/com/meilisearch/sdk/http/CustomOkHttpClient.java

Fixes #834
- It adds empty string check before adding the `Authorization` header, so to make it consistent with the default apiKey value set by the host-only Config constructor

Add check for empty API key before adding Authorization header
